import './globals.css'
import { Inter } from 'next/font/google'
import Nav from "@/components/Navigation"
import FinanceContextProvider from "@/lib/store/finance-context";
import AuthContextProvider from '@/lib/store/auth-context';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'MoneyWise',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="pt-BR">
      <body className={inter.className}>
        <AuthContextProvider>
          <FinanceContextProvider>
            <Nav />
            {children}
          </FinanceContextProvider>
        </AuthContextProvider>
      </body>
    </html>
  )
}
